//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceEdm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceEdm.Model")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SPrice {
            get {
                return this.SPriceField;
            }
            set {
                if ((this.SPriceField.Equals(value) != true)) {
                    this.SPriceField = value;
                    this.RaisePropertyChanged("SPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSPrice", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceEdm")]
    [System.SerializableAttribute()]
    public partial class ProductSPrice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdName {
            get {
                return this.IdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNameField, value) != true)) {
                    this.IdNameField = value;
                    this.RaisePropertyChanged("IdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPrice {
            get {
                return this.SPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.SPriceField, value) != true)) {
                    this.SPriceField = value;
                    this.RaisePropertyChanged("SPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductList", ReplyAction="http://tempuri.org/IService1/ProductListResponse")]
        WcfServiceEdm.ServiceReference1.Product ProductList(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductList", ReplyAction="http://tempuri.org/IService1/ProductListResponse")]
        System.Threading.Tasks.Task<WcfServiceEdm.ServiceReference1.Product> ProductListAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductAll", ReplyAction="http://tempuri.org/IService1/ProductAllResponse")]
        WcfServiceEdm.ServiceReference1.Product[] ProductAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductAll", ReplyAction="http://tempuri.org/IService1/ProductAllResponse")]
        System.Threading.Tasks.Task<WcfServiceEdm.ServiceReference1.Product[]> ProductAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductSpriceList", ReplyAction="http://tempuri.org/IService1/ProductSpriceListResponse")]
        WcfServiceEdm.ServiceReference1.ProductSPrice ProductSpriceList(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductSpriceList", ReplyAction="http://tempuri.org/IService1/ProductSpriceListResponse")]
        System.Threading.Tasks.Task<WcfServiceEdm.ServiceReference1.ProductSPrice> ProductSpriceListAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductSpriceAll", ReplyAction="http://tempuri.org/IService1/ProductSpriceAllResponse")]
        WcfServiceEdm.ServiceReference1.ProductSPrice[] ProductSpriceAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductSpriceAll", ReplyAction="http://tempuri.org/IService1/ProductSpriceAllResponse")]
        System.Threading.Tasks.Task<WcfServiceEdm.ServiceReference1.ProductSPrice[]> ProductSpriceAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfServiceEdm.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfServiceEdm.ServiceReference1.IService1>, WcfServiceEdm.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceEdm.ServiceReference1.Product ProductList(int id) {
            return base.Channel.ProductList(id);
        }
        
        public System.Threading.Tasks.Task<WcfServiceEdm.ServiceReference1.Product> ProductListAsync(int id) {
            return base.Channel.ProductListAsync(id);
        }
        
        public WcfServiceEdm.ServiceReference1.Product[] ProductAll() {
            return base.Channel.ProductAll();
        }
        
        public System.Threading.Tasks.Task<WcfServiceEdm.ServiceReference1.Product[]> ProductAllAsync() {
            return base.Channel.ProductAllAsync();
        }
        
        public WcfServiceEdm.ServiceReference1.ProductSPrice ProductSpriceList(int id) {
            return base.Channel.ProductSpriceList(id);
        }
        
        public System.Threading.Tasks.Task<WcfServiceEdm.ServiceReference1.ProductSPrice> ProductSpriceListAsync(int id) {
            return base.Channel.ProductSpriceListAsync(id);
        }
        
        public WcfServiceEdm.ServiceReference1.ProductSPrice[] ProductSpriceAll() {
            return base.Channel.ProductSpriceAll();
        }
        
        public System.Threading.Tasks.Task<WcfServiceEdm.ServiceReference1.ProductSPrice[]> ProductSpriceAllAsync() {
            return base.Channel.ProductSpriceAllAsync();
        }
    }
}
