//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpefDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KTStoreEntities : DbContext
    {
        public KTStoreEntities()
            : base("name=KTStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<ProductList_Result> ProductList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductList_Result>("ProductList");
        }
    
        public virtual ObjectResult<GetProductByName_Result> GetProductByName(string p1)
        {
            var p1Parameter = p1 != null ?
                new ObjectParameter("P1", p1) :
                new ObjectParameter("P1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductByName_Result>("GetProductByName", p1Parameter);
        }
    
        public virtual int SetSPriceById(Nullable<int> p1, Nullable<int> p2)
        {
            var p1Parameter = p1.HasValue ?
                new ObjectParameter("P1", p1) :
                new ObjectParameter("P1", typeof(int));
    
            var p2Parameter = p2.HasValue ?
                new ObjectParameter("P2", p2) :
                new ObjectParameter("P2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetSPriceById", p1Parameter, p2Parameter);
        }
    }
}
